import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Sharad Singh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Welcome back in my app</h1>
        <Link href={"https://www.google.com"}>
          <p>www.google.com</p>
        </Link>
        <p>Link to heaven</p>
        <p>Link to heaven 1</p>
      </div>
    </>
  );
}
